/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewPageIdRouteImport } from './routes/view-page.$id'
import { Route as CheckoutPlanoRouteImport } from './routes/checkout.$plano'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminGruposRouteImport } from './routes/_authenticated/admin.grupos'
import { Route as ApiPublicWebhookJson2videoRouteImport } from './routes/api/public/webhook/json2video'
import { Route as ApiPublicWebhookCaktoRouteImport } from './routes/api/public/webhook/cakto'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewPageIdRoute = ViewPageIdRouteImport.update({
  id: '/view-page/$id',
  path: '/view-page/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPlanoRoute = CheckoutPlanoRouteImport.update({
  id: '/checkout/$plano',
  path: '/checkout/$plano',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminGruposRoute =
  AuthenticatedAdminGruposRouteImport.update({
    id: '/admin/grupos',
    path: '/admin/grupos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhookJson2videoRoute =
  ApiPublicWebhookJson2videoRouteImport.update({
    id: '/api/public/webhook/json2video',
    path: '/api/public/webhook/json2video',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhookCaktoRoute = ApiPublicWebhookCaktoRouteImport.update({
  id: '/api/public/webhook/cakto',
  path: '/api/public/webhook/cakto',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/checkout/$plano': typeof CheckoutPlanoRoute
  '/view-page/$id': typeof ViewPageIdRoute
  '/admin/grupos': typeof AuthenticatedAdminGruposRoute
  '/api/public/webhook/cakto': typeof ApiPublicWebhookCaktoRoute
  '/api/public/webhook/json2video': typeof ApiPublicWebhookJson2videoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/checkout/$plano': typeof CheckoutPlanoRoute
  '/view-page/$id': typeof ViewPageIdRoute
  '/admin/grupos': typeof AuthenticatedAdminGruposRoute
  '/api/public/webhook/cakto': typeof ApiPublicWebhookCaktoRoute
  '/api/public/webhook/json2video': typeof ApiPublicWebhookJson2videoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/checkout/$plano': typeof CheckoutPlanoRoute
  '/view-page/$id': typeof ViewPageIdRoute
  '/_authenticated/admin/grupos': typeof AuthenticatedAdminGruposRoute
  '/api/public/webhook/cakto': typeof ApiPublicWebhookCaktoRoute
  '/api/public/webhook/json2video': typeof ApiPublicWebhookJson2videoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/checkout/$plano'
    | '/view-page/$id'
    | '/admin/grupos'
    | '/api/public/webhook/cakto'
    | '/api/public/webhook/json2video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/checkout/$plano'
    | '/view-page/$id'
    | '/admin/grupos'
    | '/api/public/webhook/cakto'
    | '/api/public/webhook/json2video'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/checkout/$plano'
    | '/view-page/$id'
    | '/_authenticated/admin/grupos'
    | '/api/public/webhook/cakto'
    | '/api/public/webhook/json2video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckoutPlanoRoute: typeof CheckoutPlanoRoute
  ViewPageIdRoute: typeof ViewPageIdRoute
  ApiPublicWebhookCaktoRoute: typeof ApiPublicWebhookCaktoRoute
  ApiPublicWebhookJson2videoRoute: typeof ApiPublicWebhookJson2videoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view-page/$id': {
      id: '/view-page/$id'
      path: '/view-page/$id'
      fullPath: '/view-page/$id'
      preLoaderRoute: typeof ViewPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$plano': {
      id: '/checkout/$plano'
      path: '/checkout/$plano'
      fullPath: '/checkout/$plano'
      preLoaderRoute: typeof CheckoutPlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/grupos': {
      id: '/_authenticated/admin/grupos'
      path: '/admin/grupos'
      fullPath: '/admin/grupos'
      preLoaderRoute: typeof AuthenticatedAdminGruposRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhook/json2video': {
      id: '/api/public/webhook/json2video'
      path: '/api/public/webhook/json2video'
      fullPath: '/api/public/webhook/json2video'
      preLoaderRoute: typeof ApiPublicWebhookJson2videoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/cakto': {
      id: '/api/public/webhook/cakto'
      path: '/api/public/webhook/cakto'
      fullPath: '/api/public/webhook/cakto'
      preLoaderRoute: typeof ApiPublicWebhookCaktoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminGruposRoute: typeof AuthenticatedAdminGruposRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminGruposRoute: AuthenticatedAdminGruposRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckoutPlanoRoute: CheckoutPlanoRoute,
  ViewPageIdRoute: ViewPageIdRoute,
  ApiPublicWebhookCaktoRoute: ApiPublicWebhookCaktoRoute,
  ApiPublicWebhookJson2videoRoute: ApiPublicWebhookJson2videoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
